import '/imports/api/users/expose.js';
import '/imports/api/cards/expose.js';
import '/imports/api/decks/expose.js';
import '/imports/api/deckTypes/expose.js';
import '/imports/api/cardTypes/expose.js';
import '/imports/api/tagSubscriptions/expose.js';
import '/imports/api/tags/expose.js';
import '/imports/api/tagCards/expose.js';
import '/imports/api/deckCards/expose.js'
import '/imports/api/deckDecks/expose.js'
